# Generated by Django 5.1.2 on 2024-10-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_funcionario_twitter_alter_funcionario_facebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='ferramenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('Ferramenta', models.CharField(max_length=100, verbose_name='Ferramenta')),
                ('Descricao', models.CharField(max_length=100, verbose_name='Descrição')),
                ('iconeFerramenta', models.CharField(choices=[('lni lni-rocket', 'Foguete'), ('lni lni-laptop-phone', 'Celular'), ('lni lni-cog', 'Engrenagem'), ('lni lni-leaf', 'folha'), ('lni lni-layers', 'Camadas'), ('lni lni-leaf', 'folha2')], max_length=100, verbose_name='Icone')),
            ],
            options={
                'verbose_name': 'Ferramenta',
                'verbose_name_plural': 'Ferramentas',
            },
        ),
    ]
